rakkasjs/rakkasjs

package.json
packages/cli/src/commands/build.ts
packages/cli/src/lib/config.ts
packages/cli/src/lib/importJs.ts
pnpm-lock.yaml

This PR fixes a build error on Windows.
Running `rakkas build` on Windows throws error like this:
```
node:internal/errors:464
ErrorCaptureStackTrace(err);
^
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
```
`path.resolve` on Windows returns an  absolute path that starts with drive letters like `C:` , and `import` does not accept a path with drive letters. That's why building on Windows throws the error.
In this case, appending `/` to the head of the path (like `/C:/foo/bar`) solves the problem. `vite` also uses dynamic import, but avoiding the problem to normalize a path before importing.
Similar case: https://github.com/vitejs/vite/issues/1487

fix: build error on Windows related to dynamic import

---

packages/cli/src/commands/build.ts
testbed/static/cypress/integration/static.spec.ts
testbed/static/src/pages/page.tsx
testbed/static/src/pages/styles.css

`rakkas build -d static` generates `index.html` without `<link rel="stylesheet" />` on Windows because of wrong manifest generation. This PR fixes the issue to normalize paths in the manifest.
On the current version(0.5.2), the manifest has Windows-styled paths because `path.join`(Line 208) returns a path including back shashes on Windows.
https://github.com/rakkasjs/rakkasjs/blob/58e3d05b3e96297d4d840cdcaf18f59a737b9c51/packages/cli/src/commands/build.ts#L189-L212
When collecting assets, `rakkas` uses manifest and Poisx-styled path names. The manifest has Windows-styled paths on Windows, so `assets` is always `undefined` . That's why `<link />` tags are missing. https://github.com/rakkasjs/rakkasjs/blob/eee16c59f579fea8e15871d92fb1b1d12fbd387b/packages/rakkasjs/src/server.tsx#L490-L503

Fix: wrong manifest generation on Windows for static build

---

website/src/routes/_site/guide/cloudflare-workers.page.mdx

I had some trouble figuring out how to prepare the entry-node.ts to use Cloudflare bindings.
Using the Miniflare APIs is kind of confusing by itself, as well as how to modify the createMiddleware function to include custom logic. Even the linked https://rakkasjs.org/guide/node#custom-entry page shows some code like `app.use(createMiddleware(hattipHandler))` which only works with an Express-like framework. It took me a while to realize I could just put the custom callback inside of createMiddleware function.
I think it would be nice to include a Cloudflare-specific example that does not require Express or a similar framework here.
In case it could help, I added an example based on my own experiment project here: https://github.com/patdx/edge-cms/blob/main/src/entry-node.ts But feel free to …

Add example of Cloudflare binding

---

packages/rakkasjs/src/vite-plugin/adapters.ts

As of version `0.1.0` of the runtime and `0.4.5` of the CLI, Lagon now natively supports timers APIs (https://github.com/lagonapp/lagon/pull/460).
This PR removes the `setTimeout` polyfill that isn't needed anymore.

fix: remove `setTimeout` polyfill on Lagon entry

---

packages/rakkasjs/src/features/use-query/implementation.ts

Fixes #89, which was being caused by `useQuery` returning a different object every time.

Preserve QueryResult references between calls

---

website/src/routes/_site/layout.tsx

Hi, please consider this PR for the Copyright year that was hard coded to 2021. This PR would remove the necessity to modify the year for every new year.
I am also open to work on more Javascript and especially Frontend issues or contributions, feel free to let me know!

copyright year modified using Date, not hard coded

---

website/src/routes/_site/guide/cloudflare-workers.page.mdx

It looks like Cloudflare recently refactored the integration between their Wrangler and Miniflare D1 tools.
I think the change was introduced in Miniflare 2.12.0 here: https://github.com/cloudflare/miniflare/pull/480
This change fixed my `entry-node.ts` for testing/development mode using Miniflare v2.12.1:
https://github.com/patdx/edge-cms/commit/9c40e1aaaed835e3915aa4b83165b12ae0abf5a6#diff-92da841f22f071103fd6839de1b596fc8cac0bb9679580f8a36a2ddacc052f6e
Also, here is an example of the new usage inside Wrangler CLI itself:
https://github.com/cloudflare/workers-sdk/blob/2b641765975d98e6e04342533fa088f51a96acab/packages/wrangler/src/d1/execute.tsx#L245

Update Cloudflare D1 example for Miniflare v2.12

---

packages/rakkasjs/src/features/run-server-side/lib-client.tsx
packages/rakkasjs/src/features/run-server-side/lib-common.ts
packages/rakkasjs/src/features/run-server-side/lib-server.ts
packages/rakkasjs/src/features/use-query/implementation.ts

Adds 3 new options to UseQueryOptions
Some of the description is copied from https://tanstack.com/query/v4/docs/react
enabled: Set this to `false` to disable automatic refetching when the query mounts or changes query keys. To refetch the query, use the `refetch` method returned from the `useQuery` instance. When enabled is changed from `false` to `true`, the query is refetched.
initialData: There may be times when you already have the initial data for a query available in your app and can simply provide it directly to your query. If and when this is the case, you can use the config.initialData option to set the initial data for a query and skip the initial loading state!
IMPORTANT: initialData is persisted to the cache, so it is not recommended to provide placeholder, partial or …

feat: useQuery - add enabled, initialData, placeholderData options

---

packages/rakkasjs/src/features/use-query/client-hooks.tsx

There was race condition when invalidating a query before it finished refetching
useEffect in useQueryBase was stuck with invalid = true
So if you keep pressing the "invalidate" button, invalid=true becomes stuck, and the query won't refetch anymore.

fix: race condition when invalidating queries

---

packages/rakkasjs/src/features/use-query/implementation.ts

Don't refetch when invalidating a disabled query
Don't suspend when the initial state of enabled is false and changes to true

fix: bugs related to enabled: false

---

packages/rakkasjs/src/features/run-server-side/lib-server.ts
packages/rakkasjs/src/features/run-server-side/vite-plugin.ts

When a module containing a server-side function (`useSSQ` etc.) is never used on the client, it can't be found in the module manifest, causing the build to fail. This PR fixes it by skipping the transform in such cases. Attempting to call an untransformed `runSSQ` or `useSSQ` will throw an error. `runSSM` cannot be called on the server anyway.

fix: don't crash when a server-side function is not used

---

packages/rakkasjs/src/features/pages/middleware.tsx
packages/rakkasjs/src/features/pages/vite-plugin.ts
packages/rakkasjs/src/runtime/App.tsx
packages/rakkasjs/src/runtime/hattip-handler.ts
packages/rakkasjs/src/runtime/virtual-modules.d.ts
testbed/kitchen-sink/ci.test.ts
testbed/kitchen-sink/src/routes/guarded-catch-all/$404.page.tsx
testbed/kitchen-sink/src/routes/guarded-catch-all/[...path].guard.ts
testbed/kitchen-sink/src/routes/guarded-catch-all/[...path].page.tsx
website/src/routes/_site/guide/404-handling.page.mdx
website/src/routes/_site/guide/dynamic-routes.page.mdx
website/src/routes/_site/guide/pages-and-basics.page.mdx
website/src/routes/_site/guide/route-guards.page.mdx

This PR improves 404 handling for pages and fixes an issue causing guarded catch-all routes to be matched before 404 pages.

fix: 404 and page guard interaction

---

packages/rakkasjs/src/features/run-server-side/server-hooks.ts

This PR changes the priority of `_data` routes so that they come before page routes instead of coming between page routes and API routes.
This fixes a potential bug where a page guard can prevent a `_data` route from being accessed.

fix: process data routes before page routes

---

packages/rakkasjs/src/runtime/hattip-handler.ts

This PR allows running user server hooks to run before builtin ones so that session and similar middleware can run before `_data` routes.

fix: run user server hooks before builtin ones

---

website/src/routes/_site/guide/api-routes.page.mdx

shouldn't all examples include `/api/`?
Just close if I'm mistaken

docs: fix api routes path examples

---

packages/rakkasjs/src/features/use-query/client-hooks.tsx
packages/rakkasjs/src/features/use-query/implementation.ts

When a query fails to refetch when using `useQuery` and friends, it will now keep returning the last successful data along with the last thrown error instead of throwing during render which triggers an error boundary.
This might not be always desirable but it's easier to just throw the returned error to get the old behavior than to ignore refetch errors.
Old behavior caused bad UX like showing an error (instead of data) on network disconnections or errors. It's better to hold the last fetched data along with an error indicator.

fix: don't die catastrophically when a refetch fails

---

packages/rakkasjs/src/features/pages/middleware.tsx
packages/rakkasjs/src/internal/route-utils.ts
packages/rakkasjs/src/runtime/App.tsx
testbed/kitchen-sink/ci.test.ts
testbed/kitchen-sink/src/routes/flat--route.page.tsx
testbed/kitchen-sink/src/routes/non-ascii/@[canrau].page.tsx
testbed/kitchen-sink/src/routes/non-ascii/😀.page.tsx

This PR adds support for non-ASCII characters in routes and the use of `--` for flat routes.

feat: allow non-ascii chars in routes and -- for flat routes

---

packages/rakkasjs/src/features/pages/middleware.tsx
packages/rakkasjs/src/features/run-server-side/implementation/transform/transform-client-side.test.ts
packages/rakkasjs/src/features/run-server-side/implementation/transform/transform-client-side.ts
packages/rakkasjs/src/features/run-server-side/implementation/transform/transform-server-side.test.ts
packages/rakkasjs/src/features/run-server-side/implementation/transform/transform-server-side.ts
packages/rakkasjs/src/features/run-server-side/implementation/transform/transform-utils.ts
packages/rakkasjs/src/features/run-server-side/lib-client.tsx
packages/rakkasjs/src/features/run-server-side/lib-common.ts
packages/rakkasjs/src/features/run-server-side/lib-server.ts
packages/rakkasjs/src/features/run-server-side/server-hooks.ts
packages/rakkasjs/src/features/run-server-side/vite-plugin.ts
packages/rakkasjs/src/runtime/virtual-modules.d.ts
packages/rakkasjs/src/vite-plugin/inject-config.ts
packages/rakkasjs/src/vite-plugin/resolve-client-manifest.ts
testbed/kitchen-sink/src/routes/run-ssq/index.page.tsx

This PR enables stable deploys with the `uniqueId` option in `*ServerSide*` family of functions.
Normally Rakkas uses versioned URLs for its data routes. For example, each call site for `useServerSideQuery` will generate a URL in the form of `_app/data/{BUILD_ID}/...`. This allows Rakkas to detect stale deploys and perform a full reload. But this isn't always ideal.
One way to deal with it is to keep running the old server along side the new one and use a reverse proxy or CDN in front of it to route requests to the appropriate server. But it requires quite a bit of wiring.
With this PR, it is now possible to give each call site a stable unique ID that stays identical from deploy to deploy. E.g. a `useServerSideQuery(() => { ... }, { uniqueId: "foo" })` will always map to the URL …

feat: Stable deploys

---

examples/react-query/src/entry-hattip.tsx

This PR improves the react-query integration example by switching to using `queryCache().subscribe` to track cache changes from `onSuccess`.

chore: improve react-query example

---

packages/rakkasjs/src/features/client-side-navigation/implementation.tsx
testbed/kitchen-sink/ci.test.ts
testbed/kitchen-sink/src/routes/hash-anchor/_hash-anchor.page.tsx

fix: prevent clicking native hash anchors from crashing

---

packages/rakkasjs/src/features/pages/middleware.tsx
packages/rakkasjs/src/runtime/App.tsx
testbed/kitchen-sink/src/routes/layout.tsx

The new `useRouteParams` hook's handling broke `useId` in some cases. This PR fixes it.

fix: useId mismatch

---

packages/rakkasjs/src/features/head/implementation.ts
packages/rakkasjs/src/features/head/lib.tsx
packages/rakkasjs/src/features/head/server-hooks.tsx
packages/rakkasjs/src/features/pages/middleware.tsx
packages/rakkasjs/src/runtime/hattip-handler.ts
testbed/kitchen-sink/ci.test.ts
testbed/kitchen-sink/src/routes/head/_head.page.tsx
testbed/kitchen-sink/src/routes/head/elsewhere.page.tsx
testbed/kitchen-sink/src/routes/layout.tsx
testbed/static/src/routes/layout.tsx

This PR allows setting the attributes for `<html>`, `<head>`, and `<body>` elements via the `htmlAttributes`, `headAttributes`, and `bodyAttributes` properties of the `Head` component or the `head` property of the return value of a preload function.
Example:
```ts
MainLayout.preload = (): PreloadResult => ({
head: {
htmlAttributes: { lang: "en" },
},
});
```

feat: allow setting html, head, and body attributes via Head

---

packages/rakkasjs/src/features/pages/lib.ts

I'm currently manually defining a `Params` type and would love to be able to pass that into `useRouteParams`.
What do you think? not exactly sure I think `extend` would be the right here?
Alternative could be `<T = Record<string, string>>(): T`

types: make useRouteParams generic

---

packages/rakkasjs/src/features/async-local-request-context/implementation.ts
packages/rakkasjs/src/features/async-local-request-context/lib-client.ts
packages/rakkasjs/src/features/async-local-request-context/lib-server.ts
packages/rakkasjs/src/features/async-local-request-context/server-hooks.ts
packages/rakkasjs/src/lib/client.ts
packages/rakkasjs/src/lib/index.ts
packages/rakkasjs/src/lib/server.ts
packages/rakkasjs/src/runtime/feature-server-hooks.tsx
packages/rakkasjs/src/vite-plugin/adapters.ts
packages/rakkasjs/tsup.config.ts
testbed/kitchen-sink/ci.test.ts
testbed/kitchen-sink/package.json
testbed/kitchen-sink/src/routes/alsrc/elsewhere.page.tsx
testbed/kitchen-sink/src/routes/alsrc/index.page.tsx
testbed/kitchen-sink/src/routes/run-ssq/index.page.tsx
testbed/kitchen-sink/wrangler.toml

This PR implements a new API named `getRequestContext`.
On the server, it will return the context for the current request. On the client, it will return `undefined`.
`runServerSideQuery` expects the request context as its first argument. Before this feature, the request context could only be obtained via the `useRequestContext` hook or the arguments passed to the `preload` function. This complicates the implementation of `createQueryOptions`-type APIs.
Having to pass the context argument around your server codebase everywhere it is needed also unnecessarily complicates things. This API makes it easily accessible without having to pass it around.
This feature depends on `AsyncLocalStorage` support. If it is not available, it will throw an error. Most deployment targets do support it. But …

feat: implement getRequestContext

---

examples/guide-samples/src/routes/preload/index.page.tsx
examples/todo/src/routes/todo/index.page.tsx
packages/rakkasjs/src/features/use-query/client-hooks.tsx
packages/rakkasjs/src/features/use-query/implementation.ts
packages/rakkasjs/src/features/use-query/lib.ts
packages/rakkasjs/src/features/use-query/server-hooks.tsx
testbed/kitchen-sink/src/routes/create-query/elsewhere.page.tsx
testbed/kitchen-sink/src/routes/create-query/index.page.tsx
website/src/routes/_site/guide/preload-function.page.mdx

This PR implements a new `createQuery` API.
**This is a breaking change** because it also changes how `queryClient.prefetchQuery` works (now it works much more like in TanStack Query).
Suppose you can `fetchArticle(id)` function that fetches an article from somewhere. Normally you would use it with `useQuery` like this:
```ts
const id = props.params.id;
useQuery(`article/${id}`, () => fetchArticle(id), {
cacheTime: 60_000,
staleTime: 1000,
refetchInterval: 1000,
refetchOnReconnect: true,
refetchOnWindowFocus: true,
});
```
The first problem is, you would have to repeat all the query options (like `cacheTime`, `refetchInterval` etc.) in every component you'd use `fetchArticle`.
The second problem is, you'd probably want to prefetch the query in a page's `preload` function to avoid …

feat!: createQuery function

---

packages/rakkasjs/package.json
packages/rakkasjs/src/vite-plugin/index.ts
packages/rakkasjs/src/vite-plugin/server-only-client-only.ts
pnpm-lock.yaml
testbed/kitchen-sink/ci.test.ts
testbed/kitchen-sink/src/routes/only/asset.server.txt
testbed/kitchen-sink/src/routes/only/client-only.client.ts
testbed/kitchen-sink/src/routes/only/client/only.ts
testbed/kitchen-sink/src/routes/only/index.page.tsx
testbed/kitchen-sink/src/routes/only/server-only.server.ts
testbed/kitchen-sink/src/routes/only/server/only.ts
testbed/kitchen-sink/src/routes/only/style.server.css

This PR implements server-only and client-only files.
Any module that matches the pattern `*.server.*` or `**/server/**` will have its exports turned into `undefined` in the client bundle. It is intended as an extra security layer to avoid exposing server secrets to the client.
Similarly, any module that matches the pattern `*.client.*` or `**/client/**` will have its exports turned into `undefined` in the server bundle. This is needed less often but it cn be handy for modules that use browser-only APIs at the module level, for example.
Style files (`.css`, `.scss` etc.) are not affected by this transform but asset files are.
The server-only and client-only file name patterns can be overridden with the `serverOnlyFiles` and `clientOnlyFiles` config options passed to the Rakkas Vite …

feat: server-only and client-only files

---

packages/rakkasjs/src/features/use-mutation/lib.ts
packages/rakkasjs/src/features/use-query/client-hooks.tsx
packages/rakkasjs/src/features/use-query/implementation.ts
testbed/kitchen-sink/ci.test.ts
testbed/kitchen-sink/src/routes/query-tags/index.page.tsx

This PR implements query tags. Each query can have a set of tags (which are simple string values) and they can be invalidated by those tags.
Mutations can have an `invalidateTags` option, when provided, all queries that have any of those tags in their tag set will be invalidated when the mutation settles.
react-query has a hierarchical invalidation system based on array query keys. Currently, we only support string keys. I believe tags provide a more intuitive and flexible way to invalidate a set of queries that a hierarchical system.

feat: query tags

---

packages/rakkasjs/package.json
packages/rakkasjs/src/cli/index.ts
packages/rakkasjs/src/cli/page-urls.ts
testbed/kitchen-sink/src/routes/env.page.tsx

This PR implements a new CLI command `rakkas page-urls` that generates a URL builder for creating page URLs in a type-safe manner. Currently it is very simple and brittle but I think it's pretty useful already so it's worth releasing.
**Note that you don't have to upgrade right away to use this feature.** You can simply run it with `npx rakkasjs@next page-urls` (or `pnpm dlx rakkasjs@next page-urls` etc.) in your project root. Just make sure you don't have anything important in `src/page-urls.ts` because it will be overwritten.
If you run the `rakkas page-urls` command in your project root, where `tsconfig.json` is located and `src/routes/**/*.page.tsx` are your page files, it will generate a file called `src/page-urls.ts`. It will contain a `pages` export that is a map of page names to …

feat: implement page-urls command (preliminary)

---

packages/rakkasjs/src/cli/page-urls.ts

This is the second iteration of the URL builder. The [previous design](https://github.com/rakkasjs/rakkasjs/pull/200) proved to be too cumbersome to use in real life. This PR merges path parameters, search parameters, and the hash into a single argument. So the following code:
```ts
pages.blogPostList({}, { author: "john", tag: "typescript" }, "top");
```
is now simplified to:
```ts
pages.blogPostList({ author: "john", tag: "typescript", hash: "top" });
```
In other words, there is now a single shared namespace for the path params, search params, and the hash. The parameter name `hash` is reserved for the URL hash when it's used. Despite being less flexible, it is much easier to work with.
And here's a better implementation of a type-safe link:
```tsx
import { StyledLink, StyledLinkProps …
```

feat: second iteration on URL builder

---

packages/rakkasjs/src/features/client-side-navigation/implementation.tsx
packages/rakkasjs/src/runtime/App.tsx
testbed/kitchen-sink/src/routes/query-options/index.page.tsx

This PR implements link preloading. [Link prefetching](https://github.com/rakkasjs/rakkasjs/pull/157) as previously implemented only fetches JavaScript and CSS assets for the next page. Preloading allows you to run the `preload` function as well, making the data ready for the next navigation.
It is enabled by passing a `preload` prop to the `Link` component or by passing `true` for the second argument of the `prefetchRoute` function for programmatic use. The `preload` prop can take the same values as the `prefetch` prop but it can also be set to `true` to preload when prefetching.
In Rakkas, the `preload` functions live in the page/layout modules so it's not possible to preload without also prefetching. So, if the `preload` setting is more eager than the `prefetch` setting, Rakkas will …

feat: link preloading

---

packages/rakkasjs/src/features/head/implementation/Head.tsx
packages/rakkasjs/src/features/head/implementation/types.ts
packages/rakkasjs/src/features/head/server-hooks.tsx
packages/rakkasjs/src/features/pages/middleware.tsx
packages/rakkasjs/src/features/use-query/client-hooks.tsx
packages/rakkasjs/src/features/use-query/server-hooks.tsx
packages/rakkasjs/src/lib/types.ts
packages/rakkasjs/src/runtime/App.tsx
packages/rakkasjs/src/runtime/client-entry.tsx
packages/rakkasjs/src/runtime/hattip-handler.ts

The new head handling has a head element sorter inspired by [capo.js](https://rviscomi.github.io/capo.js/) but it was only used for user-supplied elements since Rakkas itself used plain strings to serialize the preload links and other head elements it generated. With this PR, we switch to using the same logic for all head elements except those emitted by the (**now deprecated**) `emitToDocumentHead` hook.
Instead of the deprecated `emitToDocumentHead`, we now recommend `emitServerOnlyHeadElements` and `emitToSyncHeadScript`. The letter emits code inside a synchronous sloppy mode script tag in the head.
Also several scattered browser globals are now neatly tucked into a single `rakkas` global.

feat: managed head

---

packages/rakkasjs/src/features/run-server-side/lib-client.tsx
packages/rakkasjs/src/features/run-server-side/lib-common.ts
packages/rakkasjs/src/features/run-server-side/server-hooks.ts
testbed/kitchen-sink/ci.test.ts
testbed/kitchen-sink/src/routes/run-ssq/index.page.tsx

This PR allows one to set headers in server-side functions. The context object now contains a `headers` property which is an instance of the standard `Headers` object.
The main use case is to set the `cache-control` header.

feat: ability to set headers in server-side functions

---

packages/rakkasjs/src/features/client-side-navigation/implementation.tsx
packages/rakkasjs/src/features/client-side-navigation/lib.tsx
testbed/kitchen-sink/ci.test.ts
testbed/kitchen-sink/src/routes/blocker/(blocker).page.tsx
testbed/kitchen-sink/src/routes/blocker/elsewhere.page.tsx

This PR implements navigation blocking.
The `useNavigationBlocker` hook takes a condition parameter that enables navigation blocking when set to true. When enabled, the hook will return an object with `isBlocking` set to `true`. The `leave` method will allow the navigation to proceed, while the `stay` method will keep the navigation from happening.
Rakkas will also install an `onBeforeUnload` event handler if there are active navigation blockers on the page to warn the user if they close the tab or navigate away to a different site.
```tsx
const [text, setText] = useState("");
const blocker = useNavigationBlocker(text.trim() !== "");
return (
<div>
<p>
<input
type="text"
value={text}
onChange={(e) => setText(e.target.value)}
/>
&nbsp;
<button onClick={() => setText("")}>Clear</button> …
```

feat: implement navigation blocking

---

packages/rakkasjs/src/features/head/implementation/defaults.ts

This PR allows overriding the default document title via the `RAKKAS_DEFAULT_APP_TITLE` env var. This is needed because the default title ("Rakkas App") can leak to the browser in some cases (when doing client rendering or if the outermost layout throws, for example).
Currently it's a build-time setting, the runtime value of the env var is not taken into consideration. It's probably a better idea to move it into a page hook.

feat: allow overriding the default document title

---

packages/rakkasjs/src/features/pages/vite-plugin.ts
packages/rakkasjs/src/runtime/App.tsx

The old way was leaking memory and still not catching all cases. It is much cleaner to copy the new preload function into the new one.

fix: cleaner way to rerun preload functions after HMR

---

packages/rakkasjs/src/runtime/client-entry.tsx
packages/rakkasjs/src/runtime/common-hooks.ts
packages/rakkasjs/src/runtime/feature-common-hooks.ts
packages/rakkasjs/src/runtime/hattip-handler.ts
packages/rakkasjs/src/runtime/virtual-modules.d.ts
packages/rakkasjs/src/vite-plugin/rakkas-plugins.ts

`api.rakkas.xxxHooks` options now accept another form that allows to pass static configuration options to the plugin factory:
```ts
export function rakkasTanstackQuery(): Plugin {
return {
name: "my-rakkas-plugin",
api: {
rakkas: {
// Instead of
// clientHooks: "/plugin/client-hooks.tsx",
clientHooks: { 
specifier: "/plugin/client-hooks.tsx",
options: { hello: "world" },
},
},
};
}
```
The config options will be serialized with `devalue` and passed to the plugin factory function as the third (for client and server hooks) or the second (for common hooks) argument.

feat: allow Rakkas plugins to receive static config options

---

packages/rakkasjs/src/features/client-only/implementation.tsx

Use `useSyncExternalStore` instead of `useEffect` like explained in [here](https://tkdodo.eu/blog/avoiding-hydration-mismatches-with-use-sync-external-store).

fix: better implementation of ClientOnly

---

packages/rakkasjs/src/features/pages/middleware.tsx
packages/rakkasjs/src/features/run-server-side/server-hooks.ts

This PR fixes `useFormMutation` throwing a parse error in certain cases when progressive enhancement wasn't used.

fix: useFormMutation parse error

---

examples/session/readme.md
examples/session/src/routes/sign-in.page.tsx
examples/session/src/routes/sign-up.page.tsx
packages/rakkasjs/src/features/client-side-navigation/implementation/link.tsx
packages/rakkasjs/src/features/pages/middleware.tsx
packages/rakkasjs/src/internal/find-page.tsx
packages/rakkasjs/src/runtime/App.tsx
packages/rakkasjs/src/runtime/page-types.ts
testbed/kitchen-sink/src/routes/form/(form).page.tsx
testbed/kitchen-sink/src/routes/use-form-mutation/_useFormMutation.page.tsx

I still recommend returning synchronously when possible for performance reasons but async guards make a lot of things easier.
Example of synchronous return when possible:
```ts
import { userQuery } from "./user-query";
import type { User } from "./types";
import type { PageRouteGuard } from "rakkasjs";
export const pageGuard: PageRouteGuard = (ctx) => {
// We try to return synchronously if possible for better performance
function finish(user: User | null) {
if (!user) {
return {
redirect: "/login",
status: 302,
};
}
return true;
}
const user = ctx.queryClient.getQueryData(userQuery.queryKey);
if (user === undefined) {
return ctx.queryClient.ensureQueryData(userQuery).then(finish);
} else {
return finish(user);
}
};
```

feat: allow async page guards

---

packages/rakkasjs/src/features/pages/babel-remove-exports.ts
packages/rakkasjs/src/vite-plugin/index.ts
packages/rakkasjs/src/vite-plugin/routes.ts

This PR reduces the server bundle size by removing the default export of pages and layouts that are only ever used in client rendering mode.
In one Cloudflare Pages project, it cut the worker size (which ran above the limit) to less than half. In this particular app, most pages apart from the landing page and a few others are client-rendered, which is fairly typical for SaaS-type projects.
Special care was taken to ensure that `*ServerSide*` family of functions keep working despite the removal: They are hoisted to the module scope (as always) before this transform is applied.

feat: remove default export from SPA pages and layouts

---

examples/guide-samples/src/routes/client-suspense/index.page.tsx
packages/rakkasjs/src/features/client-only/implementation.tsx
packages/rakkasjs/src/features/client-only/lib.ts
packages/rakkasjs/src/features/pages/middleware.tsx
packages/rakkasjs/src/features/use-query/implementation.ts
packages/rakkasjs/src/runtime/App.tsx
packages/rakkasjs/src/runtime/client-entry.tsx
testbed/kitchen-sink/src/routes/rakkas-css/(rakkas-css).page.tsx
testbed/kitchen-sink/src/routes/use-query/index.page.tsx
website/src/lib/CodeViewer.tsx
website/src/routes/_site/guide/client-rendering.page.mdx

Rakkas used to try to await for the outermost suspense to resolve but it wasn't really working. It appears that React has no documented way of doing it. But it turns out that simply not using an outermost suspense just works.
But this required a few changes elsewhere. Most notably, the `ClientSuspense` component is now deprecated, `ClientOnly` does the exact same thing.

fix: rewrite outermost suspense awaiting logic

---

packages/rakkasjs/src/vite-plugin/inject-config.ts

With this PR, Rakkas now allows the more standard `VITE_` prefix in addition to the `RAKKAS_` prefix in environment variables exposed to the client via `import.meta.env`.

feat: allow VITE_ env prefix

---

packages/rakkasjs/src/features/client-side-navigation/implementation/history.ts
packages/rakkasjs/src/internal/find-page.tsx
packages/rakkasjs/src/lib/types.ts
packages/rakkasjs/src/runtime/App.tsx
packages/rakkasjs/src/runtime/client-entry.tsx
packages/rakkasjs/src/runtime/client-hooks.ts
packages/rakkasjs/src/runtime/common-hooks.ts
testbed/kitchen-sink/src/entry-client.ts

This PR implements two new features related to Rakkas hooks:
- `onBeforePageLookup` common hook can now be async. Same performance caveats apply as #268.
- There's now a new `onNavigation` client hook fired when a client-side navigation completes and also on initial hydration/rendering. It is useful for tracking page views and sending analytics events among other things.

feat: make some improvements for Rakkas hooks

---

packages/rakkasjs/src/features/use-query/client-hooks.tsx
packages/rakkasjs/src/features/use-query/implementation.ts

`useQuery` was returning stale data under some circumstances (probably since #273). This PR fixes it.

fix: don't return stale value from useQuery

---

packages/rakkasjs/src/runtime/feature-server-hooks.tsx

fix: sort server hooks to prepare `ctx.fetch` before calling ssq

---

packages/rakkasjs/src/features/client-side-navigation/implementation/link.tsx

This PR makes the `StyledLink` function accept functions for the `className` and `style` props, making state-dependent styling easier.
The functions are passed an object with two boolean properties `isCurrent` and `isPending`.
The old styling props `activeClass`, `pendingClass`, `pendingStyle`, and `activeStyle` are now deprecated.

feat: make StyledLink accept functions for className and style props
